[build]
  publish = "."

[[edge_functions]]
  function = "content"
  path = "/api/content"

[[edge_functions]]
  function = "blog-posts"
  path = "/api/blog-posts"

[[redirects]]
  from = "https://blog.weareverveco.com/*"
  to = "https://www.blog.weareverveco.com/:splat"
  status = 301
  force = true
